<?php
declare(strict_types=1);
$slug=trim((string)($_GET['slug']??''));
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tourism business · JomCommunicate</title><link rel="stylesheet" href="assets/css/styles.css"></head><body class="public-business"><main class="content-wrap public-wrap"><a class="brand-inline" href="index.php">JC · JomCommunicate</a><div id="publicStatus" class="card-panel"><h1>Loading business information…</h1></div><section id="publicBusiness" hidden><div class="page-heading"><div><span class="eyebrow">Account-free tourism business page</span><h1 id="publicName"></h1><p id="publicDescription"></p></div></div><div class="grid-two"><article class="card-panel"><h2>Service information</h2><dl class="details-list"><dt>Category</dt><dd id="publicCategory"></dd><dt>Address</dt><dd id="publicAddress"></dd><dt>Services</dt><dd id="publicServices"></dd><dt>Payment methods</dt><dd id="publicPayments"></dd><dt>Menu explanations</dt><dd id="publicMenu"></dd><dt>Facilities</dt><dd id="publicFacilities"></dd></dl></article><article class="card-panel"><h2>Ask with approved phrases</h2><label>Your language<select id="publicLanguage"><option value="en">English</option><option value="ms">Bahasa Malaysia</option><option value="zh">Mandarin Chinese</option><option value="id">Indonesian</option><option value="th">Thai</option></select></label><div id="publicPhrases" class="scenario-steps"></div></article></div><div class="grid-two mt"><article class="card-panel"><h2>Frequently asked questions</h2><div id="publicFaqs" class="record-list"></div></article><article class="card-panel"><h2>Local terminology</h2><div id="publicTerms" class="record-list"></div></article></div></section></main><div id="messageOverlay" class="emergency-overlay" aria-hidden="true"><button id="closeOverlay">×</button><strong id="overlaySource"></strong><strong id="overlayTranslation"></strong><span id="overlayExtra"></span></div>
<script>
const slug=<?=json_encode($slug,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?>,$=s=>document.querySelector(s),esc=v=>{const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML};
async function load(){const r=await fetch('api/public_business.php?slug='+encodeURIComponent(slug));const d=await r.json();if(!r.ok){$('#publicStatus').innerHTML='<h1>Business page unavailable</h1><p>'+esc(d.message)+'</p>';return;}$('#publicStatus').hidden=true;$('#publicBusiness').hidden=false;const b=d.business;for(const [id,key] of Object.entries({publicName:'name',publicDescription:'description',publicCategory:'category',publicAddress:'address',publicServices:'service_details',publicPayments:'payment_methods',publicMenu:'menu_details',publicFacilities:'facility_details'}))$('#'+id).textContent=b[key]||'Not provided';render(d);}
function render(d){const lang=$('#publicLanguage').value,items=d.phrases.filter(x=>x.target_language===lang||lang==='en');$('#publicPhrases').innerHTML=(items.length?items:d.phrases).map(x=>'<button class="scenario-step public-phrase" data-id="'+x.id+'" data-category="'+esc(x.category)+'" data-question="'+esc(x.source_text)+'"><strong>'+esc(x.source_text)+'</strong><span>'+esc(x.translated_text)+'</span></button>').join('')||'<div class="empty-state">No approved phrases.</div>';$('#publicFaqs').innerHTML=d.faqs.map(x=>'<details><summary>'+esc(x.question)+'</summary><p>'+esc(x.answer)+'</p></details>').join('')||'No FAQs.';$('#publicTerms').innerHTML=d.terms.map(x=>'<div class="record-item"><div><strong>'+esc(x.term)+'</strong><small>'+esc(x.explanation)+'</small></div></div>').join('')||'No terms.';document.querySelectorAll('.public-phrase').forEach(x=>x.onclick=async()=>{const row=(items.length?items:d.phrases).find(p=>String(p.id)===x.dataset.id);$('#overlaySource').textContent=row.translated_text;$('#overlayTranslation').textContent=row.suggested_reply||'';$('#overlayExtra').textContent='Approved business quick reply';$('#messageOverlay').classList.add('open');await fetch('api/public_business.php?slug='+encodeURIComponent(slug),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({category:x.dataset.category,language:$('#publicLanguage').value,question:x.dataset.question})});});$('#publicLanguage').onchange=()=>render(d);}
$('#closeOverlay').onclick=()=>$('#messageOverlay').classList.remove('open');load();
</script></body></html>
