"use client";

import { useEffect, useState } from "react";
import Image from "next/image";
import QRCode from "qrcode";
import { BarChart3, BriefcaseBusiness, Check, ChevronRight, Copy, Download, Heart, Languages, MapPinned, Mic, Play, Plus, QrCode, ShieldCheck, Sparkles, Trash2, TriangleAlert, Volume2, X } from "lucide-react";

type ModuleKey = "communicate" | "assistant" | "business" | "journey" | "insights" | "admin";
type RecordItem = { id: number; type: string; title: string; status: string; payload: Record<string, unknown>; createdAt?: string };
type SaveFn = (type: string, title: string, payload: Record<string, unknown>, status?: string) => Promise<void>;
type NotifyFn = (message: string) => void;

const modules: { key: ModuleKey; label: string; icon: typeof Languages }[] = [
  { key: "communicate", label: "Communication", icon: Languages },
  { key: "assistant", label: "Smart assistance", icon: Sparkles },
  { key: "business", label: "Business portal", icon: BriefcaseBusiness },
  { key: "journey", label: "My journey", icon: MapPinned },
  { key: "insights", label: "Insights", icon: BarChart3 },
  { key: "admin", label: "Administration", icon: ShieldCheck },
];

const translations: Record<string, string> = {
  "where is the train station?": "Di manakah stesen kereta api?",
  "how much is this?": "Berapakah harga ini?",
  "i need help": "Saya perlukan bantuan",
  "i am allergic to peanuts": "Saya alah kepada kacang tanah",
  "no pork please": "Tolong jangan letak daging khinzir",
  "thank you": "Terima kasih",
  hello: "Helo",
  "can i pay by card?": "Boleh saya bayar dengan kad?",
};
const scenarios = ["General", "Restaurant", "Hotel", "Transport", "Shopping", "Medical", "Emergency"];
const phrases = [
  ["Where is the nearest station?", "Di manakah stesen terdekat?"],
  ["Can I pay by card?", "Boleh saya bayar dengan kad?"],
  ["Please speak slowly", "Tolong bercakap perlahan-lahan"],
  ["I need medical assistance", "Saya perlukan bantuan perubatan"],
];

function TabBar({ tabs, value, onChange }: { tabs: string[]; value: string; onChange: (v: string) => void }) {
  return <div className="segmented" role="tablist">{tabs.map(t => <button key={t} className={value === t ? "active" : ""} onClick={() => onChange(t)}>{t}</button>)}</div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return <div className="field"><label>{label}</label>{children}</div>;
}
function SectionHead({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) {
  return <div className="page-head"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2><p>{description}</p></div></div>;
}

export default function Workspace() {
  const [active, setActive] = useState<ModuleKey>("communicate");
  const [role, setRole] = useState("Tourist");
  const [records, setRecords] = useState<RecordItem[]>([]);
  const [toast, setToast] = useState("");

  useEffect(() => { fetch("/api/records").then(r => r.ok ? r.json() : Promise.reject()).then(raw => { const d = raw as { records?: RecordItem[] }; setRecords(d.records ?? []); }).catch(() => undefined); }, []);
  const notify: NotifyFn = message => { setToast(message); window.setTimeout(() => setToast(""), 2400); };
  const save: SaveFn = async (type, title, payload, status = "active") => {
    const optimistic: RecordItem = { id: Date.now(), type, title, payload, status, createdAt: new Date().toISOString() };
    setRecords(r => [optimistic, ...r]);
    try {
      const response = await fetch("/api/records", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ type, title, payload, status }) });
      if (response.ok) { const data = await response.json() as { record: RecordItem }; setRecords(r => r.map(x => x.id === optimistic.id ? data.record : x)); }
    } catch { /* retains the visible result when the demonstration database is unavailable */ }
    notify(`${title} saved`);
  };
  const remove = async (id: number) => { setRecords(r => r.filter(x => x.id !== id)); await fetch(`/api/records?id=${id}`, { method: "DELETE" }).catch(() => undefined); notify("Item removed"); };
  const current = modules.find(m => m.key === active)!;

  return <div className="shell">
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark">MY</div><div><div className="brand-name">JomCommunicate</div><div className="brand-sub">Malaysia travel companion</div></div></div>
      <nav className="nav" aria-label="Main navigation">{modules.map(m => { const Icon = m.icon; return <button key={m.key} className={active === m.key ? "active" : ""} onClick={() => setActive(m.key)}><Icon size={18}/><span>{m.label}</span></button>; })}</nav>
      <div className="sidebar-foot"><small>Inclusive communication for confident travel across Malaysia.</small></div>
    </aside>
    <main className="main">
      <header className="topbar"><h1>{current.label}</h1><div className="role-switch"><span>Demo view</span><select className="select" value={role} onChange={e => setRole(e.target.value)} aria-label="Select demo role"><option>Tourist</option><option>Business Representative</option><option>Tourism Stakeholder</option><option>Administrator</option></select><div className="avatar">WS</div></div></header>
      <div className="content">
        {active === "communicate" && <Communication save={save} notify={notify}/>} 
        {active === "assistant" && <Assistant save={save} notify={notify}/>} 
        {active === "business" && <Business records={records} save={save} remove={remove} notify={notify}/>} 
        {active === "journey" && <Journey records={records} save={save} remove={remove} notify={notify}/>} 
        {active === "insights" && <Insights records={records} save={save} notify={notify}/>} 
        {active === "admin" && <Admin records={records} save={save} remove={remove} notify={notify}/>} 
      </div>
    </main>
    <nav className="mobile-nav" aria-label="Mobile navigation">{modules.map(m => { const Icon = m.icon; return <button key={m.key} aria-label={m.label} className={active === m.key ? "active" : ""} onClick={() => setActive(m.key)}><Icon size={19}/></button>; })}</nav>
    {toast && <div className="toast" role="status">{toast}</div>}
  </div>;
}

function Communication({ save, notify }: { save: SaveFn; notify: NotifyFn }) {
  const [tab, setTab] = useState("Text translation");
  const [source, setSource] = useState("Where is the train station?");
  const [result, setResult] = useState("Di manakah stesen kereta api?");
  const [scenario, setScenario] = useState("Transport");
  const [confidence, setConfidence] = useState(96);
  const [listening, setListening] = useState(false);
  const [report, setReport] = useState(false);
  const doTranslate = () => { const found = translations[source.trim().toLowerCase()]; const output = found ?? `[Malay] ${source}`; setResult(output); setConfidence(found ? 96 : 72); save("translation", source, { source, result: output, scenario, confidence: found ? 96 : 72 }, "completed"); };
  const speak = (text: string) => { if ("speechSynthesis" in window) { speechSynthesis.cancel(); speechSynthesis.speak(new SpeechSynthesisUtterance(text)); } notify("Playing translation aloud"); };
  const listen = () => {
    type SpeechResult = { results: { 0: { 0: { transcript: string } } } };
    type Recognition = { lang: string; start: () => void; onresult: (e: SpeechResult) => void; onend: () => void };
    const speechWindow = window as typeof window & { webkitSpeechRecognition?: new () => Recognition };
    if (!speechWindow.webkitSpeechRecognition) { notify("Speech recognition is unavailable in this browser"); return; }
    const recognition = new speechWindow.webkitSpeechRecognition(); recognition.lang = "en-MY"; setListening(true);
    recognition.onresult = e => setSource(e.results[0][0].transcript); recognition.onend = () => setListening(false); recognition.start();
  };
  return <>
    <SectionHead eyebrow="Real-time communication" title="Make every conversation easier." description="Translate text or speech, switch between tourism scenarios, review uncertain results and report unclear translations."/>
    <TabBar tabs={["Text translation","Voice conversation","Local glossary"]} value={tab} onChange={setTab}/>
    {tab === "Text translation" && <div className="grid two">
      <div className="card"><div className="grid two"><Field label="From"><select className="select"><option>English</option><option>Malay</option><option>Mandarin</option><option>Tamil</option></select></Field><Field label="To"><select className="select"><option>Malay</option><option>English</option><option>Mandarin</option><option>Tamil</option></select></Field></div><Field label="Message"><textarea className="textarea" value={source} onChange={e => setSource(e.target.value)} placeholder="Type a message…"/></Field><div className="chips" style={{marginBottom:14}}>{scenarios.map(s => <button className={`chip ${scenario === s ? "active" : ""}`} key={s} onClick={() => setScenario(s)}>{s}</button>)}</div><div className="actions"><button className="btn primary" onClick={doTranslate}><Languages size={15}/>Translate</button><button className="btn ghost" onClick={listen}><Mic size={15}/>{listening ? "Listening…" : "Speak"}</button></div></div>
      <div className="card"><h3>Translation</h3><p className="small muted">Detected English · {scenario} scenario</p><div className="result"><div className="translation">{result}</div><small>{confidence}% confidence {confidence < 80 ? "· Please review" : "· High confidence"}</small></div><div className="actions" style={{marginTop:14}}><button className="btn ghost" onClick={() => navigator.clipboard?.writeText(result).then(() => notify("Copied"))}><Copy size={15}/>Copy</button><button className="btn ghost" onClick={() => speak(result)}><Volume2 size={15}/>Play</button><button className="btn ghost" onClick={() => setReport(true)}><TriangleAlert size={15}/>Report unclear</button></div></div>
    </div>}
    {tab === "Voice conversation" && <div className="grid two"><div className="card soft"><div className="eyebrow">Participant A · English</div><h3 style={{fontSize:24,marginTop:10}}>{source}</h3><button className="btn primary" onClick={listen}><Mic size={16}/>{listening ? "Listening…" : "Hold to speak"}</button></div><div className="card"><div className="eyebrow">Participant B · Malay</div><h3 style={{fontSize:24,marginTop:10}}>{result}</h3><div className="actions"><button className="btn secondary" onClick={doTranslate}>Translate turn</button><button className="btn ghost" onClick={() => speak(result)}><Play size={15}/>Play</button></div></div></div>}
    {tab === "Local glossary" && <div className="grid three">{[["Mamak","A casual Indian-Muslim eatery, often open late."],["Surau","A smaller Muslim prayer room."],["Tapau","To pack food for takeaway."],["Touch 'n Go","A cashless payment card used for transport and tolls."],["Kopitiam","A traditional local coffee shop."],["Pedas","Spicy; ask for ‘kurang pedas’ for less spicy."]].map(([term,meaning]) => <div className="card" key={term}><div className="eyebrow">Malaysian term</div><h3 style={{marginTop:8}}>{term}</h3><p className="muted small">{meaning}</p><button className="btn ghost" onClick={() => speak(term)}><Volume2 size={14}/>Pronounce</button></div>)}</div>}
    {report && <div className="modal-backdrop"><div className="modal"><div className="actions" style={{justifyContent:"space-between"}}><h3>Report unclear translation</h3><button className="btn ghost" onClick={() => setReport(false)}><X size={15}/></button></div><Field label="What went wrong?"><select className="select"><option>Wrong meaning</option><option>Unclear wording</option><option>Local term missing</option><option>Speech recognition error</option></select></Field><Field label="Suggested correction (optional)"><textarea className="textarea" placeholder="Help us understand the issue"/></Field><div className="notice">The report is stored without direct personal identifiers.</div><div className="actions" style={{marginTop:16}}><button className="btn primary" onClick={() => { save("issue", "Unclear translation", {source,result,scenario}, "pending"); setReport(false); }}>Submit report</button><button className="btn ghost" onClick={() => setReport(false)}>Cancel</button></div></div></div>}
  </>;
}

function Assistant({ save, notify }: { save: SaveFn; notify: NotifyFn }) {
  const [tab, setTab] = useState("Guided scenario"); const [scenario, setScenario] = useState("Restaurant");
  const [dietary, setDietary] = useState<string[]>(["Halal"]); const [emergency, setEmergency] = useState(false); const [pack, setPack] = useState("Kuala Lumpur");
  const toggle = (v: string) => setDietary(x => x.includes(v) ? x.filter(i => i !== v) : [...x,v]);
  return <><SectionHead eyebrow="Smart tourism assistance" title="Know what to say next." description="Use guided scenarios, quick replies, dietary cards, emergency communication and downloadable destination phrase packs."/><TabBar tabs={["Guided scenario","Dietary & allergy","Emergency card","Offline packs"]} value={tab} onChange={setTab}/>
    {tab === "Guided scenario" && <div className="grid two"><div className="card"><Field label="Tourism scenario"><select className="select" value={scenario} onChange={e=>setScenario(e.target.value)}>{scenarios.slice(1).map(s=><option key={s}>{s}</option>)}</select></Field><h4>What would you like to do?</h4><div className="chips">{["Ask for a table","Read a menu","Ask about payment","Request directions","Check availability"].map(x=><button className="chip" key={x} onClick={()=>notify(`${x} selected`)}>{x}</button>)}</div></div><div className="card soft"><div className="eyebrow">Suggested next questions</div>{phrases.slice(0,3).map(([a,b])=><div key={a} style={{padding:"14px 0",borderBottom:"1px solid #d5e7e2"}}><strong>{a}</strong><div className="muted small" style={{margin:"5px 0 9px"}}>{b}</div><div className="actions"><button className="btn secondary" onClick={()=>notify("Phrase opened in communication")}>Use phrase <ChevronRight size={14}/></button><button className="btn ghost" onClick={()=>save("favourite",a,{source:a,translation:b},"saved")}><Heart size={14}/>Save</button></div></div>)}</div></div>}
    {tab === "Dietary & allergy" && <div className="grid two"><div className="card"><h3>Select requirements</h3><p className="muted small">Choose all that apply. Add a serious allergy only after confirming its severity.</p><div className="chips" style={{margin:"18px 0"}}>{["Halal","Vegetarian","No pork","No alcohol","Less spicy","Peanut allergy","Shellfish allergy"].map(x=><button className={`chip ${dietary.includes(x)?"active":""}`} onClick={()=>toggle(x)} key={x}>{dietary.includes(x)&&<Check size={12} style={{display:"inline",marginRight:5}}/>}{x}</button>)}</div><button className="btn primary" onClick={()=>save("dietary", "Dietary communication card", {requirements:dietary}, "active")}>Generate bilingual message</button></div><div className="card"><div className="result"><div><small>SHOW THIS TO STAFF</small><div className="translation" style={{marginTop:12}}>I require: {dietary.join(", ") || "No selections"}</div><p>Saya perlukan: {dietary.join(", ") || "Tiada pilihan"}</p></div><small>Please confirm serious allergies directly with staff.</small></div></div></div>}
    {tab === "Emergency card" && <div className="card"><div className="grid two"><div><div className="eyebrow">Urgent assistance</div><h3 style={{fontSize:28,marginTop:8}}>Create a card people can understand quickly.</h3><p className="muted">Select a situation, add only the necessary information, then display or play the bilingual card.</p></div><div><Field label="Emergency type"><select className="select"><option>Medical assistance</option><option>Lost person</option><option>Police assistance</option><option>Transport emergency</option></select></Field><Field label="Important detail"><input className="input" defaultValue="I feel dizzy and need a doctor."/></Field><button className="btn danger" onClick={()=>setEmergency(true)}><TriangleAlert size={16}/>Generate emergency card</button></div></div></div>}
    {tab === "Offline packs" && <div className="grid two"><div className="card"><Field label="Destination"><select className="select" value={pack} onChange={e=>setPack(e.target.value)}><option>Kuala Lumpur</option><option>Penang</option><option>Melaka</option><option>Sabah</option><option>Sarawak</option></select></Field><p className="muted small">42 essential phrases · Food, transport, accommodation and emergency · 1.8 MB</p><button className="btn primary" onClick={()=>save("pack",`${pack} phrase pack`,{destination:pack,version:"1.2",phrases:42},"installed")}><Download size={15}/>Download pack</button></div><div className="card"><h3>Phrase preview</h3>{phrases.map(([a,b])=><div key={a} style={{padding:"11px 0",borderBottom:"1px solid #edf1ef"}}><strong className="small">{a}</strong><div className="muted small">{b}</div></div>)}</div></div>}
    {emergency&&<div className="modal-backdrop"><div className="modal"><div className="emergency"><TriangleAlert size={42} color="#b13b3b"/><h3>MEDICAL HELP NEEDED</h3><p style={{fontSize:19}}>I feel dizzy and need a doctor.</p><hr/><h3>PERLUKAN BANTUAN PERUBATAN</h3><p style={{fontSize:19}}>Saya pening dan memerlukan doktor.</p></div><div className="actions" style={{marginTop:16,justifyContent:"center"}}><button className="btn primary" onClick={()=>notify("Playing emergency message")}><Volume2 size={15}/>Play aloud</button><button className="btn ghost" onClick={()=>setEmergency(false)}>Close</button></div></div></div>}
  </>;
}

function Business({ records, save, remove, notify }: { records: RecordItem[]; save: SaveFn; remove: (id:number)=>Promise<void>; notify: NotifyFn }) {
  const [tab,setTab]=useState("Profile"); const [business,setBusiness]=useState("Bunga Raya Café"); const [qr,setQr]=useState(""); const [content,setContent]=useState("Do you accept card payments?");
  const makeQr=async()=>{const url=`https://example.com/business/${business.toLowerCase().replace(/[^a-z0-9]+/g,"-")}`;setQr(await QRCode.toDataURL(url,{width:280,margin:1,color:{dark:"#102d2a",light:"#ffffff"}}));save("business",business,{url,category:"Food & beverage"},"pending");};
  const businessContent=records.filter(r=>r.type==="business-content");
  return <><SectionHead eyebrow="Tourism business communication" title="Help every visitor understand your business." description="Manage verified information, publish multilingual phrases, create QR access and review communication performance."/><TabBar tabs={["Profile","QR access","Phrases & FAQs","Reports"]} value={tab} onChange={setTab}/>
    {tab==="Profile"&&<div className="grid two"><div className="card"><h3>Business registration</h3><p className="muted small">Complete the details below. New registrations enter the administrator review queue.</p><Field label="Business name"><input className="input" value={business} onChange={e=>setBusiness(e.target.value)}/></Field><div className="grid two"><Field label="Category"><select className="select"><option>Food & beverage</option><option>Hotel</option><option>Transport</option><option>Tour operator</option></select></Field><Field label="Supported languages"><input className="input" defaultValue="Malay, English, Mandarin"/></Field></div><Field label="Public description"><textarea className="textarea" defaultValue="Local Malaysian dishes, fresh coffee and tourist-friendly service."/></Field><div className="actions"><button className="btn primary" onClick={()=>save("business",business,{category:"Food & beverage",languages:["Malay","English","Mandarin"]},"pending")}>Submit for review</button><button className="btn ghost" onClick={()=>notify("Draft saved")}>Save draft</button></div></div><div className="card soft"><div className="eyebrow">Public preview</div><h3 style={{fontSize:26,marginTop:9}}>{business}</h3><span className="badge">Food & beverage</span><p className="muted">Open today · 8:00 am–10:00 pm</p><div className="grid two"><div className="stat"><span className="small muted">Languages</span><strong>3</strong></div><div className="stat"><span className="small muted">Published FAQs</span><strong>{Math.max(8,businessContent.length)}</strong></div></div></div></div>}
    {tab==="QR access"&&<div className="grid two"><div className="card"><h3>Generate public QR access</h3><p className="muted small">Tourists can scan this code and view approved business information without creating an account.</p><Field label="Business page"><input className="input" value={business} onChange={e=>setBusiness(e.target.value)}/></Field><button className="btn primary" onClick={makeQr}><QrCode size={15}/>Generate QR code</button></div><div className="card" style={{textAlign:"center"}}>{qr?<><Image src={qr} alt={`QR code for ${business}`} width={230} height={230} unoptimized style={{maxWidth:"100%",height:"auto",margin:"0 auto"}}/><h3>{business}</h3><div className="actions" style={{justifyContent:"center"}}><a className="btn secondary" href={qr} download="business-qr.png"><Download size={14}/>Download PNG</a><button className="btn ghost" onClick={()=>notify("Public page opened")}>Preview page</button></div></>:<div className="empty"><QrCode size={42} style={{margin:"0 auto 12px"}}/><p>Generate a code to see the public-page preview.</p></div>}</div></div>}
    {tab==="Phrases & FAQs"&&<div className="grid two"><div className="card"><h3>Add communication content</h3><Field label="Content type"><select className="select"><option>Frequently asked question</option><option>Quick reply</option><option>Malaysian term</option><option>Guided phrase</option></select></Field><Field label="Source text"><textarea className="textarea" value={content} onChange={e=>setContent(e.target.value)}/></Field><Field label="Malay translation"><input className="input" defaultValue="Adakah anda menerima pembayaran kad?"/></Field><button className="btn primary" onClick={()=>save("business-content",content,{translation:"Adakah anda menerima pembayaran kad?",category:"FAQ"},"pending")}>Submit for moderation</button></div><div className="card"><h3>Content library</h3><div className="table-wrap"><table><thead><tr><th>Content</th><th>Status</th><th></th></tr></thead><tbody>{businessContent.length?businessContent.map(r=><tr key={r.id}><td>{r.title}</td><td><span className={`badge ${r.status==="pending"?"pending":""}`}>{r.status}</span></td><td><button className="btn ghost" onClick={()=>remove(r.id)}><Trash2 size={13}/></button></td></tr>):<tr><td colSpan={3} className="empty">No submitted content yet.</td></tr>}</tbody></table></div></div></div>}
    {tab==="Reports"&&<Insights records={records} save={save} notify={notify} compact/>}
  </>;
}

function Journey({ records, save, remove, notify }: { records: RecordItem[]; save: SaveFn; remove: (id:number)=>Promise<void>; notify: NotifyFn }) {
  const [tab,setTab]=useState("Profile"); const favs=records.filter(r=>r.type==="favourite"); const packs=records.filter(r=>r.type==="pack");
  return <><SectionHead eyebrow="Personalised tourist and journey" title="Your travel preferences, under your control." description="Manage language and accessibility settings, save phrases, prepare destination packs and control consent or deletion."/><TabBar tabs={["Profile","Needs & access","Saved phrases","Destination packs","Privacy"]} value={tab} onChange={setTab}/>
    {tab==="Profile"&&<div className="grid two"><div className="card"><h3>Tourist profile</h3><div className="grid two"><Field label="Display name"><input className="input" defaultValue="Wei Shen"/></Field><Field label="Preferred language"><select className="select"><option>English</option><option>Malay</option><option>Mandarin</option><option>Tamil</option></select></Field></div><Field label="Current destination"><select className="select"><option>Kuala Lumpur</option><option>Penang</option><option>Melaka</option><option>Sabah</option></select></Field><button className="btn primary" onClick={()=>save("profile","Tourist profile",{language:"English",destination:"Kuala Lumpur"},"active")}>Save preferences</button></div><div className="card soft"><h3>Continue as guest</h3><p className="muted small">Translation and guided assistance work without an account. Saved phrases, synchronised packs and profile preferences require a registered session.</p><div className="notice">This demonstration keeps personal fields minimal and separates them from anonymous analytics.</div></div></div>}
    {tab==="Needs & access"&&<div className="card"><h3>Accessibility and personal needs</h3><p className="muted small">Optional information is used only for the purposes you select.</p><div className="grid two"><div><h4>Communication settings</h4>{["Large text","Read results aloud","Slower speech playback","High-contrast cards"].map(x=><label key={x} style={{display:"block",padding:"8px 0"}}><input type="checkbox"/> {x}</label>)}</div><div><h4>Personal needs</h4>{["Halal meals","Vegetarian meals","Mobility assistance","Peanut allergy"].map(x=><label key={x} style={{display:"block",padding:"8px 0"}}><input type="checkbox"/> {x}</label>)}</div></div><div className="actions" style={{marginTop:14}}><button className="btn primary" onClick={()=>save("accessibility","Accessibility settings",{largeText:true,readAloud:true},"active")}>Save consented settings</button><button className="btn ghost">Clear optional data</button></div></div>}
    {tab==="Saved phrases"&&<div className="card"><div className="actions" style={{justifyContent:"space-between",marginBottom:14}}><h3>Saved phrases</h3><button className="btn primary" onClick={()=>save("favourite","Where is the nearest station?",{translation:"Di manakah stesen terdekat?",label:"Transport"},"saved")}><Plus size={14}/>Add sample</button></div><div className="table-wrap"><table><thead><tr><th>Phrase</th><th>Translation</th><th>Category</th><th></th></tr></thead><tbody>{favs.length?favs.map(r=><tr key={r.id}><td>{r.title}</td><td>{String(r.payload.translation??"")}</td><td><span className="badge">{String(r.payload.label??"Saved")}</span></td><td><button className="btn ghost" onClick={()=>remove(r.id)}><Trash2 size={13}/></button></td></tr>):<tr><td colSpan={4} className="empty">Save a phrase from Communication or Smart Assistance.</td></tr>}</tbody></table></div></div>}
    {tab==="Destination packs"&&<div className="grid three">{["Kuala Lumpur","Penang","Melaka"].map((x,i)=>{const installed=packs.some(p=>p.title.startsWith(x));return <div className="card" key={x}><div className="eyebrow">{42+i*8} phrases · {(1.8+i*.3).toFixed(1)} MB</div><h3 style={{marginTop:8}}>{x}</h3><p className="muted small">Food, transport, hotel, shopping and emergency phrases.</p><button className={`btn ${installed?"secondary":"primary"}`} onClick={()=>installed?notify("Pack is up to date"):save("pack",`${x} phrase pack`,{destination:x,version:"1.2"},"installed")}>{installed?<><Check size={14}/>Installed</>:<><Download size={14}/>Download</>}</button></div>})}</div>}
    {tab==="Privacy"&&<div className="grid two"><div className="card"><h3>Consent controls</h3>{[["Improve translations","Allow anonymous quality signals"],["Personal suggestions","Use saved preferences in recommendations"],["Journey history","Synchronise recent activity across sessions"]].map(([a,b],i)=><label key={a} style={{display:"flex",gap:12,padding:"13px 0",borderBottom:"1px solid #edf1ef"}}><input type="checkbox" defaultChecked={i<2}/><span><strong className="small">{a}</strong><span className="small muted" style={{display:"block",marginTop:3}}>{b}</span></span></label>)}<button className="btn primary" style={{marginTop:15}} onClick={()=>save("consent","Consent settings",{analytics:true,personalisation:true,history:false},"active")}>Update consent</button></div><div className="card"><h3>Delete personal data</h3><p className="muted small">Delete selected history or submit an account-deletion request. Irreversible actions always require confirmation.</p><button className="btn ghost" onClick={()=>notify("Selected history deleted")}>Delete journey history</button><button className="btn danger" style={{marginLeft:8}} onClick={()=>confirm("Request account deletion? This action cannot be undone.")&&notify("Account deletion request submitted")}>Delete account</button></div></div>}
  </>;
}

function Insights({ records, save, notify, compact=false }: { records: RecordItem[]; save: SaveFn; notify: NotifyFn; compact?: boolean }) {
  const [period,setPeriod]=useState("Last 30 days"); const issues=Math.max(18,records.filter(r=>r.type==="issue").length);
  const exportCsv=()=>{const rows=[["Metric","Value"],["Interactions","1284"],["Unclear translations",String(issues)],["Top language","Mandarin"],["Peak period","12:00–14:00"]];const blob=new Blob([rows.map(r=>r.join(",")).join("\n")],{type:"text/csv"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="communication-report.csv";a.click();notify("CSV report downloaded");};
  return <>{!compact&&<SectionHead eyebrow="Communication intelligence" title="Turn communication gaps into better service." description="Review anonymous trends, repeated enquiries, peak periods and evidence-backed improvement recommendations."/>}<div className="actions" style={{marginBottom:18}}><select className="select" style={{width:180}} value={period} onChange={e=>setPeriod(e.target.value)}><option>Last 7 days</option><option>Last 30 days</option><option>Last 90 days</option></select><select className="select" style={{width:180}}><option>All scenarios</option><option>Restaurant</option><option>Transport</option><option>Hotel</option></select><button className="btn ghost" onClick={exportCsv}><Download size={14}/>Export CSV</button><button className="btn ghost" onClick={()=>window.print()}><Download size={14}/>Print / PDF</button></div>
    <div className="grid four" style={{marginBottom:18}}>{[["Total interactions","1,284","+12%"],["Translation success","94.6%","+2.1%"],["Unclear reports",String(issues),"−8%"],["Languages supported","4","Stable"]].map(([a,b,c])=><div className="stat" key={a}><span className="small muted">{a}</span><strong>{b}</strong><span className="trend">{c} · {period}</span></div>)}</div>
    <div className="grid two"><div className="card"><h3>Communication gaps</h3><p className="muted small">Aggregated issue categories; groups below the privacy threshold are suppressed.</p>{[["Local food terms",78],["Transport directions",61],["Payment questions",44],["Allergy communication",31]].map(([a,b])=><div key={String(a)} style={{margin:"17px 0"}}><div className="actions" style={{justifyContent:"space-between",marginBottom:7}}><span className="small">{a}</span><strong className="small">{b}</strong></div><div className="bar"><span style={{width:`${b}%`}}/></div></div>)}</div><div className="card"><h3>Peak communication periods</h3><p className="muted small">Demand by time band across approved location groups.</p><div style={{display:"flex",alignItems:"end",gap:13,height:190,paddingTop:20}}>{[35,52,84,96,71,48,62,42].map((h,i)=><div key={i} style={{flex:1,textAlign:"center"}}><div style={{height:h*1.45,background:i===3?"#0d6f63":"#b7d9d1",borderRadius:"7px 7px 2px 2px"}}></div><span style={{fontSize:9,color:"#687572"}}>{8+i*2}:00</span></div>)}</div></div></div>
    <div className="card" style={{marginTop:18}}><div className="actions" style={{justifyContent:"space-between"}}><div><div className="eyebrow">Evidence-backed recommendation</div><h3 style={{marginTop:7}}>Add clearer payment and dietary quick replies</h3></div><span className="badge pending">Under review</span></div><p className="muted small">Supported by 44 repeated payment enquiries and 31 allergy-related interactions during the selected period. Target: Smart Assistance and Business Content.</p><div className="actions"><button className="btn primary" onClick={()=>save("recommendation","Add payment and dietary quick replies",{period,evidence:75,target:"Smart Assistance"},"accepted")}>Accept recommendation</button><button className="btn ghost" onClick={()=>notify("Recommendation marked for review")}>Keep under review</button><button className="btn ghost" onClick={()=>notify("Recommendation rejected with rationale")}>Reject</button></div></div>
  </>;
}

function Admin({ records, save, remove, notify }: { records: RecordItem[]; save: SaveFn; remove: (id:number)=>Promise<void>; notify: NotifyFn }) {
  const [tab,setTab]=useState("Overview"); const pendingBusinesses=records.filter(r=>r.type==="business"&&r.status==="pending"); const moderation=records.filter(r=>r.type==="business-content"&&r.status==="pending");
  const sampleBusinesses: RecordItem[] = [{id:991,type:"business",title:"Warisan Hotel",status:"pending",payload:{category:"Hotel"}},{id:992,type:"business",title:"Penang Food Walk",status:"pending",payload:{category:"Tour operator"}}];
  const sampleContent: RecordItem[] = [{id:993,type:"business-content",title:"Can I pay by card?",status:"pending",payload:{}},{id:994,type:"business-content",title:"Contains shellfish",status:"pending",payload:{}}];
  return <><SectionHead eyebrow="Protected administration" title="Keep the platform trusted and accountable." description="Review registrations and content, manage roles, configure privacy rules and inspect audit events or service health."/><TabBar tabs={["Overview","Registrations","Moderation","Users & roles","Privacy rules","Audit & health"]} value={tab} onChange={setTab}/>
    {tab==="Overview"&&<><div className="grid four">{[["Pending registrations",String(Math.max(3,pendingBusinesses.length))],["Content reviews",String(Math.max(7,moderation.length))],["Active users","1,842"],["Service health","99.98%"]].map(([a,b])=><div className="stat" key={a}><span className="small muted">{a}</span><strong>{b}</strong><span className="trend">View details</span></div>)}</div><div className="grid two" style={{marginTop:18}}><div className="card"><h3>Review queue</h3>{["Bunga Raya Café registration","Payment FAQ translation","Melaka phrase pack update"].map((x,i)=><div className="actions" key={x} style={{justifyContent:"space-between",padding:"13px 0",borderBottom:"1px solid #edf1ef"}}><span className="small">{x}</span><span className={`badge ${i<2?"pending":""}`}>{i<2?"Pending":"Scheduled"}</span></div>)}</div><div className="card"><h3>System health</h3>{[["Translation service","Operational"],["Speech service","Operational"],["Database","Operational"],["Analytics pipeline","Delayed 3 min"]].map(([a,b],i)=><div className="actions" key={a} style={{justifyContent:"space-between",padding:"12px 0",borderBottom:"1px solid #edf1ef"}}><span className="small">{a}</span><span className={`badge ${i===3?"pending":""}`}>{b}</span></div>)}</div></div></>}
    {tab==="Registrations"&&<div className="card"><h3>Business registration queue</h3><div className="table-wrap"><table><thead><tr><th>Business</th><th>Category</th><th>Evidence</th><th>Status</th><th>Decision</th></tr></thead><tbody>{(pendingBusinesses.length?pendingBusinesses:sampleBusinesses).map(r=><tr key={r.id}><td><strong>{r.title}</strong></td><td>{String(r.payload.category??"Food & beverage")}</td><td>Complete</td><td><span className="badge pending">Pending</span></td><td><div className="actions"><button className="btn secondary" onClick={()=>{save("admin-decision",`Approved ${r.title}`,{recordId:r.id},"approved");if(r.id<900)remove(r.id);}}>Approve</button><button className="btn ghost" onClick={()=>notify("Returned for correction with reason")}>Return</button><button className="btn ghost" onClick={()=>notify("Registration rejected with reason")}>Reject</button></div></td></tr>)}</tbody></table></div></div>}
    {tab==="Moderation"&&<div className="card"><h3>Phrase and FAQ moderation</h3><div className="table-wrap"><table><thead><tr><th>Submitted content</th><th>Language coverage</th><th>Context</th><th>Action</th></tr></thead><tbody>{(moderation.length?moderation:sampleContent).map(r=><tr key={r.id}><td>{r.title}</td><td>English · Malay</td><td>Business FAQ</td><td><div className="actions"><button className="btn secondary" onClick={()=>{save("moderation",`Approved: ${r.title}`,{recordId:r.id},"approved");if(r.id<900)remove(r.id);}}>Approve</button><button className="btn ghost" onClick={()=>notify("Content returned with correction reason")}>Request correction</button></div></td></tr>)}</tbody></table></div></div>}
    {tab==="Users & roles"&&<div className="card"><h3>User and role management</h3><div className="table-wrap"><table><thead><tr><th>User</th><th>Current role</th><th>Status</th><th>Allowed change</th></tr></thead><tbody>{[["Aisyah Rahman","Business Representative","Active"],["Daniel Tan","Tourism Stakeholder","Active"],["Mei Lin Wong","Tourist","Active"],["System Reviewer","Administrator","Protected"]].map(([a,b,c])=><tr key={a}><td><strong>{a}</strong></td><td>{b}</td><td><span className={`badge ${c==="Protected"?"danger":""}`}>{c}</span></td><td><select className="select" disabled={c==="Protected"} onChange={()=>notify("Role updated; affected sessions revoked")}><option>Choose action</option><option>Change role</option><option>Suspend account</option><option>Reactivate account</option></select></td></tr>)}</tbody></table></div><div className="notice" style={{marginTop:14}}>Protected roles cannot be changed from this screen. Privileged changes require re-authentication and a recorded reason.</div></div>}
    {tab==="Privacy rules"&&<div className="grid two"><div className="card"><h3>Active privacy configuration</h3><Field label="Analytics retention"><select className="select"><option>90 days</option><option>180 days</option><option>365 days</option></select></Field><Field label="Minimum analytical group"><input className="input" type="number" defaultValue={10}/></Field><Field label="Location granularity"><select className="select"><option>Approved area group</option><option>State only</option></select></Field><Field label="Change rationale"><textarea className="textarea" placeholder="Required for the audit trail"/></Field><button className="btn primary" onClick={()=>save("privacy-rule","Privacy configuration v1.4",{retentionDays:90,minGroup:10,location:"area"},"active")}>Validate and activate</button></div><div className="card soft"><div className="eyebrow">Impact summary</div><h3 style={{marginTop:8}}>No identifying message content retained</h3><p className="muted small">Groups with fewer than 10 interactions are suppressed or combined. Previous rule versions remain available for audit review.</p><div className="notice">Reducing the group threshold may increase disclosure risk and requires secondary approval.</div></div></div>}
    {tab==="Audit & health"&&<div className="grid two"><div className="card"><div className="actions" style={{justifyContent:"space-between"}}><h3>Audit events</h3><button className="btn ghost" onClick={()=>notify("Authorised audit export prepared")}><Download size={14}/>Export</button></div>{[["Business registration reviewed","Administrator","2 min ago"],["Privacy configuration viewed","Administrator","18 min ago"],["Report exported","Stakeholder","1 hr ago"],["Role change rejected","System","3 hrs ago"]].map(([a,b,c])=><div key={a} style={{padding:"13px 0",borderBottom:"1px solid #edf1ef"}}><strong className="small">{a}</strong><div className="small muted" style={{marginTop:4}}>{b} · {c}</div></div>)}</div><div className="card"><h3>Service availability</h3>{[["Translation API",99.99],["Speech recognition",99.94],["Data store",100],["Report service",99.87]].map(([a,b])=><div key={String(a)} style={{margin:"18px 0"}}><div className="actions" style={{justifyContent:"space-between",marginBottom:7}}><span className="small">{a}</span><strong className="small">{b}%</strong></div><div className="bar"><span style={{width:`${b}%`}}/></div></div>)}<button className="btn secondary" onClick={()=>save("escalation","Report service latency",{service:"Report service",severity:"low"},"open")}>Record follow-up</button></div></div>}
  </>;
}
