<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');
require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../config/validation.php';
function public_reply(array $b,int $s=200):never{http_response_code($s);echo json_encode($b,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
try{
 $slug=clean_text($_GET['slug']??'',100,true);$db=database();$stmt=$db->prepare("SELECT id,name,category,address,description,service_details,payment_methods,menu_details,facility_details,qr_slug FROM businesses WHERE qr_slug=? AND verification_status='approved' AND is_public=1 LIMIT 1");$stmt->execute([$slug]);$b=$stmt->fetch();if(!$b)public_reply(['ok'=>false,'message'=>'Business page not found.'],404);$bid=(int)$b['id'];
 $method=$_SERVER['REQUEST_METHOD']??'GET';
 if($method==='POST'){$input=json_decode((string)file_get_contents('php://input'),true);if(!is_array($input))public_reply(['ok'=>false,'message'=>'Invalid JSON body.'],400);$category=clean_text($input['category']??'General',80,true);$language=isset($input['language'])?clean_language($input['language']):null;$question=clean_text($input['question']??'',250);$token=!empty($input['requires_reply'])&&$question!==''?bin2hex(random_bytes(16)):null;$db->prepare('INSERT INTO business_interactions(business_id,category,language_code,question_label,public_token) VALUES(?,?,?,?,?)')->execute([$bid,$category,$language,$question?:null,$token]);public_reply(['ok'=>true,'question_token'=>$token,'status'=>$token?'new':null]);}
 if($method!=='GET'){header('Allow: GET, POST');public_reply(['ok'=>false,'message'=>'Method not allowed.'],405);}
 if(isset($_GET['question_token'])){$token=clean_text($_GET['question_token'],32,true);if(!preg_match('/^[a-f0-9]{32}$/',$token))public_reply(['ok'=>false,'message'=>'Invalid question reference.'],422);$question=$db->prepare('SELECT status,reply_text,answered_at,updated_at FROM business_interactions WHERE business_id=? AND public_token=? LIMIT 1');$question->execute([$bid,$token]);$answer=$question->fetch();if(!$answer)public_reply(['ok'=>false,'message'=>'Question not found.'],404);public_reply(['ok'=>true,'question'=>$answer]);}
 $p=$db->prepare('SELECT id,target_language,source_text,translated_text,suggested_reply,category FROM business_phrases WHERE business_id=? AND is_published=1 ORDER BY category,id');$p->execute([$bid]);$f=$db->prepare('SELECT id,question,answer,language_code FROM business_faqs WHERE business_id=? AND is_published=1 ORDER BY id');$f->execute([$bid]);$t=$db->prepare('SELECT term,explanation,language_code FROM business_terms WHERE business_id=? AND is_published=1 ORDER BY term');$t->execute([$bid]);$translations=$db->prepare('SELECT language_code,description,service_details,payment_methods,menu_details,facility_details FROM business_profile_translations WHERE business_id=?');$translations->execute([$bid]);unset($b['id']);public_reply(['ok'=>true,'business'=>$b,'translations'=>$translations->fetchAll(),'phrases'=>$p->fetchAll(),'faqs'=>$f->fetchAll(),'terms'=>$t->fetchAll()]);
}catch(InvalidArgumentException $e){public_reply(['ok'=>false,'message'=>$e->getMessage()],422);}catch(Throwable $e){error_log('Public business: '.$e->getMessage());public_reply(['ok'=>false,'message'=>'Business page unavailable.'],500);}
